### ISSUE TITLE
I get this error when I run "npm run dev". Please help me!

### ISSUE THREAD

**Issue by NguyenNgocVan279** [MuhaddiMu/Portfolio#11]
![error-npm-run-dev](https://user-images.githubusercontent.com/70937652/131384771-94603423-a280-440c-b53d-830dcfc6bceb.png)

**Comment by MuhaddiMu** [comment]
Hi @NguyenNgocVan279 Can you try removing the `node modules` and reinstall using the command `npm install`?

I have just checked it on the fresh host and it's working for me.

**Comment by MuhaddiMu** [comment]
Hi @NguyenNgocVan279  Thank you for creating an issue. 

It was a problem with the Nuxt Eslint Module.  I have resolved all the outdated  dependencies in the commit https://github.com/MuhaddiMu/Portfolio/commit/0dd0c989458021f9172b678d9ff2675ad4c84847

Try to pull the recent changes, remove the node modules and reinstall the fresh dependencies using `$ npm i`

Let me know if that works for you.

**Comment by NguyenNgocVan279** [comment]
Dear MuhaddiMu,
I clone the total Project after the update of  #0dd0c98. The old error does not appear, but the new error occurs (image attach). I try to search google but can not find the way to fix it. Please help me one more time. Thank you very much!
![error](https://user-images.githubusercontent.com/70937652/131451511-ec7568c7-69e2-4a4a-81c9-c9cef0217141.png)

**Comment by MuhaddiMu** [comment]
Yes, I am also facing this warning and unfortunately, there is nothing I can do regarding these errors. 

For now, this is the only workaround I have come up with. I have posted regarding this in the issue https://github.com/nuxt/content/issues/106#issuecomment-663873586 

There's a Nuxt plugin that might help resolve this issue https://www.npmjs.com/package/@nuxt/friendly-errors-webpack-plugin?activeTab=readme

I'd appreciate it if you can contribute to this project by fixing these warnings. You can still run the development and make changes as you like.

**Comment by MuhaddiMu** [comment]
Maybe this comment can help resolve those warnings
https://github.com/nuxt/content/issues/106#issuecomment-666283547

**Comment by NguyenNgocVan279** [comment]
Yes. I will try. Thank you, MuhaddiMu. Good luck and good health!
